# Generated by Django 5.2.5 on 2025-09-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='enable_compression',
            field=models.BooleanField(default=False, help_text='Enable video compression before encryption'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('READY', 'READY')], default='processing', max_length=20),
        ),
    ]
