version: '3.8'

services:
  django:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
      - ./backend:/app
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/4
      - PACKAGER_SERVICE_URL=http://packager:8080
    depends_on:
      redis:
        condition: service_started
      packager:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: ./backend
    volumes:
      - ./backend/media:/app/media
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/4
      - PACKAGER_SERVICE_URL=http://packager:8080
    depends_on:
      redis:
        condition: service_started
      packager:
        condition: service_healthy
    command: celery -A server worker --loglevel=info

  packager:
    build:
      context: ./packager
    image: packager:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - ./backend/media:/work/media
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request,sys; urllib.request.urlopen('http://localhost:8080/health', timeout=2); sys.exit(0)"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"

# No named volumes required; we use a bind mount so all services share ./backend/media
